### ISSUE TITLE
License

### ISSUE THREAD

**Issue by a3f** [carstenz/ev3sensor#1]
Hello  Carstenz,

What's the license on your sensor code?

Thanks.

**Comment by carstenz** [comment]
Hi!

I've added the GNU GPLv3 license now. Some of the header files are snippets taken from the Lego Mindstorms source code which is under that license, and I had forgotten to add it. ( https://github.com/mindboards/ev3sources )
- Carsten

**Comment by a3f** [comment]
A bit late but thanks!

We have integrated your library into a more complete solution over at [https://c4ev3.github.io](https://c4ev3.github.io). Feel free to check it out :-)

**Comment by carstenz** [comment]
That's really cool, nice work!
